WebApplication1/Controllers/BusinessFrontController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BusinessFrontController : Controller
    {
        private WebApplicationContext db = new WebApplicationContext();
        // GET: BusinessFront
        public ActionResult Index()
        {
            List<Product> result = new List<Product>();
            result = (from p in db.Products select p).ToList();
            return View(result);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CNBM International Trading Limited</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/otherjs")
    @RenderSection("scripts", required: false)
    <!--[if lt IE 9]>
        <script src="~/Scripts/html5shiv.min.js"></script>
        <script src="~/Scripts/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 overflow">
                    <div class="social-icons pull-right">
                        <ul class="nav nav-pills">
                            <li><a href=""><i class="fa fa-facebook"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                            <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                            <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">
                        <h1><img src="~/Images/logo.png" alt="logo"></h1>
                    </a>

                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="dropdown">
                            <a href="@Url.Action("About", "Home")">About Us <i class="fa fa-angle-down"></i></a>
                            <ul role="menu" class="sub-menu">
                                <li>@Html.ActionLink("About Us", "About", "Home")</li>
                                <li>@Html.ActionLink("Corporate Culture", "Culture", "Home")</li>
                                <li>@Html.ActionLink("Corporate Strategy", "Strategy", "Home")</li>
                                <li>@Html.ActionLink("Marketing Network", "Network", "Home")</li>
                                <li>@Html.ActionLink("Vision & Mission", "Vision", "Home")</li>
                                <li></li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Business", "Index", "BusinessFront")</li>
                        <li>@Html.ActionLink("Careers", "Careers", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    </ul>
                </div>
                <div class="search">
                    <form role="form">
                        <i class="fa fa-search"></i>
                        <div class="field-toggle">
                            <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center bottom-separator">
                    <img src="~/Images/home/under.png" class="img-responsive inline" alt="">
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="testimonial bottom">
                        <h2>What Our Customers Say</h2>
                        <div class="media">
                            <div class="pull-left">
                                <a href="#"><img src="~/Images/home/profile1.jpg" alt=""></a>
                            </div>
                            <div class="media-body">
                                <blockquote>The team at CNBM Trading are absolute pleasure to deal with. It was exactly as it was advertised. Would recommend to anyone.</blockquote>
                                <h3><a href="#">- Kim Peeby</a></h3>
                            </div>
                        </div>
                        <div class="media">
                            <div class="pull-left">
                                <a href="#"><img src="~/Images/home/profile2.jpg" alt=""></a>
                            </div>
                            <div class="media-body">
                                <blockquote>Great service. Very satifid with everything. We will be back for more and tells others as well.</blockquote>
                                <h3><a href="">- David Mebrat</a></h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="contact-info bottom">
                        <h2>Contacts</h2>
                        <address>
                            E-mail: <a href="mailto:zhudi@outlook.com">zhudi@outlook.com</a> <br />
                            Phone: +64 022 015 0885 <br />
                        </address>
                        <h2>Address</h2>
                        <address>
                            50 Princes Street, <br>
                            Onehunga, <br>
                            Auckland, 1061 <br>
                            New Zealand <br>
                        </address>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="contact-form bottom">
                        <h2>Send a message</h2>
                        <form id="main-contact-form" name="contact-form" method="post" action="sendemail.php">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <input type="email" name="email" class="form-control" required="required" placeholder="Email Id">
                            </div>
                            <div class="form-group">
                                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your text here"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-submit" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-sm-12 copyright-text text-center">
                    <p>&copy; CNBM International Trading Limited @DateTime.Now.Year. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>